name: Deploy Continuo a PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Forzar actualización en PythonAnywhere vía API
      run: |
        curl -X POST "https://www.pythonanywhere.com/api/v0/user/JeferEsqui93/webapps/JeferEsqui93.pythonanywhere.com/reload/" \
          -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}"